apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: java-hello-world
      buildpacks:
        builder: docker.io/briandealwis/gcp-base:latest

# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./k8s/**.yaml
